project:
  type: website
  output-dir: docs

website:
  title: "Covid-19 Observable Test"
  navbar:
    type: dark
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: [styles.css, custom.scss]
    toc: true

editor: visual

